### ISSUE TITLE
compile.bat编译失败

### ISSUE THREAD

**Issue by asdqp233** [FCMRIP/HK-Arknights#4]
修改完hook.cpp后复制过去并运行 compile.bat ，编译失败,然后这个窗口就没了
![1](https://i.loli.net/2021/10/30/uvtq19zxGZN3hSp.png)

**Comment by long45343** [comment]
检查一下目录

**Comment by asdqp233** [comment]
> 检查一下目录

指的是Android-hooking-template/obj/local/arkeabi-v7a/objs/hook目录吗?
里面没有任何文件

**Comment by long45343** [comment]
检查一下.bat脚本有没有设置

**Comment by asdqp233** [comment]
> 检查一下.bat脚本有没有设置

修改过第一行的ndk文件夹地址了

**Comment by long45343** [comment]
按着教程检查一下吧
我也不太清楚

**Comment by asdqp233** [comment]
> 按着教程检查一下吧
> 我也不太清楚

那我周末再试一下 谢谢
