### ISSUE TITLE
您好，我按照您的教程完成了以后，游戏一打开就闪退

### ISSUE THREAD

**Issue by jeffhiei** [FCMRIP/HK-Arknights#6]
您好，我按照您的教程完成了以后，游戏一打开过一会就提示游戏已停止运行，请问是不是我哪里做错了，或者教程过时了，望回复，非常感谢！

**Comment by long45343** [comment]
x86架构和arm架构要分别编译

**Comment by jeffhiei** [comment]
> x86架构和arm架构要分别编译

我是仅打包了x86的.so库，arm未作修改，且我仅在模拟器上使用，这样难道也要编译arm框架嘛？

**Comment by long45343** [comment]
你模拟器上的可能是arm转译

**Comment by jeffhiei** [comment]
> 你模拟器上的可能是arm转译

我是雷电模拟器4.0.67，那我去尝试一下mumu模拟器。非常感谢您的指导，我是未成年玩家，能有您这样的大佬真的太幸运了！

**Comment by jeffhiei** [comment]
> 你模拟器上的可能是arm转译

我编译成功了 ，但是貌似这次更新以后鹰角更改了方案，这样已经不能登陆了，会提示用户信息已模糊
