### ISSUE TITLE
是否考虑过用github actions实现个人自己构建？

### ISSUE THREAD

**Issue by SherkeyXD** [FCMRIP/HK-Arknights#8]
如题，如果不想被盗取，这也许是唯一延续项目的做法

或者打压缩包，到爱发点获取解压密码什么的
总之还是很希望项目能恢复，自己编译老是报错...

**Comment by SherkeyXD** [comment]
见到过一个用ga 让fork者自己构建apk的例子
https://github.com/LSPosed/MagiskOnWSA

**Comment by long45343** [comment]
莫得
不考虑盈利
主要是这种行为违法而且我也不需要了
