### ISSUE TITLE
疑似，11.1后破解防沉迷失效？

### ISSUE THREAD

**Issue by Alkaid-Star** [FCMRIP/HK-Arknights#9]
如题，感谢您在之前的日子里作出的贡献。
但是11月1日后方舟进行大更新需要重新下载客户端。
据说是提升了反破解防沉迷的手段。。
请问这个项目还能继续做下去破解防沉迷么
如果可以的话请尽快发布最新版安装包QAQ
谢谢啦！

**Comment by 24kkkkkkk** [comment]
话说这个号是从taou0那里接手的还是这就是他本人？希望大佬能尽快吧😞

**Comment by long45343** [comment]
不是本人
我只是看着教程的（
我成年了（
